### ISSUE TITLE
ldap plugin can not list all the operational attributes in the results

### ISSUE THREAD

**Issue by zhujian0805** [turbot/steampipe-plugin-ldap#18]
ldap plugin can not list all the operational attributes in the results

**for example, without the '+' i can not see the operational attributes
`ldapsearch -b 'ou=users,dc=example,dc=net' 'user=me'
`but with '+' i can
`ldapsearch -b 'ou=users,dc=example,dc=net' 'user=me' '+'`

So I tried '["memberof"]' and '["+"]' didn't work.

**Comment by graza-io** [comment]
Hi @zhujian0805 

> NOTE: Please ensure you censor confidential information in any details/info you pass over

Would you be able to elaborate on this issue a bit, information I'm looking for would be:
- The query you attempted
- The expected result set
- The actual result set
- Any errors you observed running the query

Not required but would be beneficial would be the `debug` level logs of the query execution, you can set Steampipe to output `debug` logs with the [STEAMPIPE_LOG_LEVEL](https://steampipe.io/docs/reference/env-vars/steampipe_log) environment variable.

Logs can then be located in the `~/.steampipe/logs` dir.

**Comment by graza-io** [comment]
Hey @zhujian0805 I'm going to close this issue for now as no response received, please feel free to reopen this if you feel there's anything additional you can add so we can dig into your issue(s).

Thanks!
