### ISSUE TITLE
Add table ldap_computer

### ISSUE THREAD

**Issue by matteoredaelli** [turbot/steampipe-plugin-ldap#4]
Many Ldap servers ( active directory) contains "computer" objects: for instance all windows workstations and servers that are joined to the Windows Domain. 

It would be nice to have a table ldap_computer (filtered with "(objectclass=computer)" ?)

Sample fields
```
dn: CN=7WK011,OU=DESKTOPS,DC=example,DC=com
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
objectClass: computer
cn: 7WK011
distinguishedName: CN=7WK011,OU=DESKTOPS,DC=example,DC=com
name: 7WK011
operatingSystem: Windows 7 Enterprise
operatingSystemVersion: 6.1 (7601)
operatingSystemServicePack: Service Pack 1
dNSHostName: 7WK011.example.com
```

**Comment by e-gineer** [comment]
@matteoredaelli Agree it would be great to add this table - thanks for the suggestion!

Is there a standard set of field names with descriptions that we can look to implement? Feels like something that may vary a lot between LDAP / AD / etc provider, so would be great to have some "definitive" source to base our implementation on...

**Comment by matteoredaelli** [comment]
In any LDAP implementations you can extend their schema adding  with new objectclass...
About the objectClass "Computer" for M$, you can find the fields at https://docs.microsoft.com/en-us/windows/win32/adschema/c-computer 
The most useful / populated fields (in the AD server I use) are listed at the top of the "issue"

Thanks
Matteo
