### ISSUE TITLE
function getOrganizationUnit crash if DN does not contains OU and no results will returned

### ISSUE THREAD

**Issue by harlequin** [turbot/steampipe-plugin-ldap#9]
**Describe the bug**
getOrganizationUnit crash if DN does not contains OU

```golang
func getOrganizationUnit(dn string) string {
	return dn[strings.Index(strings.ToUpper(dn), "OU"):]  // Here the function will crash in case OU not exists
}
```

Proposal is to change to logic like

```golang
func getOrganizationUnit(dn string) string {
	index := strings.Index(strings.ToUpper(dn), "OU")
	if index > -1 {
		return dn[index:]
	} else {
		return ""
	}
}
```

**Comment by misraved** [comment]
Thanks @harlequin for using Steampipe 👍 

We will look into this issue and provide you with feedback shortly.

**Comment by misraved** [comment]
Thanks @harlequin for catching the issue 👍 .

The solution seems correct. Would you like to make the change by creating a pull request with the above-suggested logic?

Would really appreciate your contribution here 👍.

**Comment by harlequin** [comment]
PR is generated
